<?php
$baseUrl = '/enfermaria/public/index.php';
$nome = $_SESSION['user_name'] ?? 'Administrador';
$query = http_build_query(['route' => 'admin_hospital_transfers_pdf', 'from' => $fromDate, 'to' => $toDate]);
?>
<!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Encaminhamentos hospitalares</title>
<link rel="stylesheet" href="/enfermaria/public/assets/css/layout.css">
<link rel="stylesheet" href="/enfermaria/public/assets/css/admin-lists.css?v=20260929-2">
<style>
.hospital-list .filters form{column-gap:20px}.hospital-list .filters input{box-sizing:border-box}
.hospital-list .filters form{grid-template-columns:repeat(2,minmax(180px,1fr)) auto}.hospital-list table{min-width:1120px;table-layout:fixed}.hospital-list th:nth-child(1){width:10%}.hospital-list th:nth-child(2){width:18%}.hospital-list th:nth-child(3){width:14%}.hospital-list th:nth-child(4){width:23%}.hospital-list th:nth-child(5){width:12%}.hospital-list th:nth-child(6){width:16%}.hospital-list th:nth-child(7){width:7%}.hospital-list .patient-cell strong{display:block;color:#10213f}.hospital-list .muted{color:#718096;font-size:.76rem}.outcome{display:inline-block;padding:5px 8px;border-radius:999px;font-size:.72rem;font-weight:800;white-space:nowrap}.outcome.accepted{background:#e7f8ef;color:#13734e}.outcome.refused{background:#fff0e6;color:#a34b0b}.description-cell{white-space:normal}.description-preview{display:inline-block;margin-top:3px;border-bottom:1px dotted #8796aa;cursor:help}.readable-tooltip{position:fixed;z-index:3000;display:none;width:max-content;max-width:min(420px,calc(100vw - 32px));padding:10px 12px;border:1px solid #334b68;border-radius:7px;background:#102a46;color:#fff;box-shadow:0 10px 28px rgba(7,24,43,.28);font-family:"Segoe UI",Arial,sans-serif;font-size:14px;font-weight:400;line-height:1.45;white-space:normal;pointer-events:none}.hospital-list .export-button{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 15px;border-radius:7px;background:#18885f;color:#fff;text-decoration:none;font-size:.85rem;font-weight:700;white-space:nowrap}.hospital-list .export-button:hover{background:#116b4a;text-decoration:none}@media(max-width:1100px){.hospital-list .filters form{grid-template-columns:repeat(2,minmax(0,1fr))}.hospital-list .filter-actions{grid-column:1/-1}}@media(max-width:720px){.hospital-list .filters form{display:flex}}
</style></head><body class="list-view">
<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="list-page hospital-list">
 <div class="list-heading"><div><span class="list-eyebrow">Administração</span><h1>Encaminhamentos hospitalares</h1><p class="subtitle">Ocorrências com encaminhamento hospitalar registado, incluindo recusas.</p></div><span class="result-count"><?= count($incidents) ?> resultado<?= count($incidents)===1?'':'s' ?></span></div>
 <div class="filters"><form method="get" action="<?= $baseUrl ?>"><input type="hidden" name="route" value="admin_hospital_transfers"><div><label for="from">Data inicial</label><input id="from" type="date" name="from" value="<?= htmlspecialchars($fromDate) ?>"></div><div><label for="to">Data final</label><input id="to" type="date" name="to" value="<?= htmlspecialchars($toDate) ?>"></div><div class="filter-actions"><button type="submit">Pesquisar</button><a class="btn-reset" href="<?= $baseUrl ?>?route=admin_hospital_transfers">Limpar</a><a class="export-button" target="_blank" href="<?= $baseUrl ?>?<?= htmlspecialchars($query) ?>">Imprimir PDF</a></div></form></div>
 <?php if ($incidents===[]): ?><div class="empty-state">Não foram encontrados encaminhamentos no período selecionado.</div><?php else: ?>
 <div class="table-card"><div class="table-scroll"><table><thead><tr><th>Episódio</th><th>Ocorrência</th><th>Utente</th><th>Contacto / identificação</th><th>Enfermeiro</th><th>Tratamentos / observações</th><th>Resultado</th></tr></thead><tbody>
 <?php foreach($incidents as $i): ?><?php $description=(string)($i['description']?:'Sem descrição'); $descriptionPreview=mb_strlen($description)>30?mb_substr($description,0,30).'…':$description; $treatments=(string)($i['treatments_summary']?:'—'); $treatmentsPreview=mb_strlen($treatments)>30?mb_substr($treatments,0,30).'…':$treatments; ?><tr><td><a href="<?= $baseUrl ?>?route=admin_incident_detail&id=<?= (int)$i['id'] ?>">#<?= (int)$i['episode_number'] ?></a><div class="muted"><?= htmlspecialchars($i['occurred_at']) ?></div></td><td><strong><?= htmlspecialchars($i['incident_type_name']) ?></strong><div class="muted"><?= htmlspecialchars($i['location_name']) ?></div><div class="description-cell"><span class="description-preview" tabindex="0" data-tooltip="<?= htmlspecialchars($description,ENT_QUOTES,'UTF-8') ?>" aria-label="Descrição completa: <?= htmlspecialchars($description,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($descriptionPreview) ?></span></div></td><td class="patient-cell"><strong><?= htmlspecialchars($i['patient_name'] ?: '—') ?></strong><div class="muted"><?= htmlspecialchars($i['patient_dob'] ?: '—') ?> · <?= htmlspecialchars($i['patient_gender'] ?: '—') ?><br><?= htmlspecialchars($i['patient_nationality'] ?: '—') ?><?= !empty($i['patient_is_employee'])?' · Colaborador':'' ?></div></td><td><?= htmlspecialchars($i['patient_phone'] ?: '—') ?><div class="muted"><?= htmlspecialchars(trim(($i['patient_address']??'').' '.($i['patient_postal_code']??'').' '.($i['patient_city']??'')) ?: '—') ?><br><?= htmlspecialchars(trim(($i['patient_id_type']??'').' '.($i['patient_id_number']??'')) ?: '—') ?></div></td><td><?= htmlspecialchars($i['nurse_name']) ?></td><td class="description-cell"><span class="description-preview" tabindex="0" data-tooltip="<?= htmlspecialchars($treatments,ENT_QUOTES,'UTF-8') ?>" aria-label="Tratamentos e observações completos: <?= htmlspecialchars($treatments,ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($treatmentsPreview) ?></span></td><td><span class="outcome <?= !empty($i['refused_hospital'])?'refused':'accepted' ?>"><?= !empty($i['refused_hospital'])?'Recusado':'Encaminhado' ?></span><div class="muted"><?= htmlspecialchars($i['hospital_recorded_at'] ?: '') ?></div></td></tr><?php endforeach; ?>
 </tbody></table></div></div><?php endif; ?>
</main><div class="readable-tooltip" id="description-tooltip" role="tooltip"></div><script>
(()=>{const tooltip=document.getElementById('description-tooltip');const targets=document.querySelectorAll('[data-tooltip]');const show=(target)=>{tooltip.textContent=target.dataset.tooltip||'';tooltip.style.display='block';const rect=target.getBoundingClientRect();const box=tooltip.getBoundingClientRect();let left=Math.min(rect.left,window.innerWidth-box.width-16);left=Math.max(16,left);let top=rect.bottom+8;if(top+box.height>window.innerHeight-16)top=rect.top-box.height-8;tooltip.style.left=left+'px';tooltip.style.top=Math.max(16,top)+'px';};const hide=()=>{tooltip.style.display='none';};targets.forEach(target=>{target.addEventListener('mouseenter',()=>show(target));target.addEventListener('mouseleave',hide);target.addEventListener('focus',()=>show(target));target.addEventListener('blur',hide);});window.addEventListener('scroll',hide,true);})();
</script></body></html>
