<?php
$monthNames = [1=>'Janeiro',2=>'Fevereiro',3=>'Março',4=>'Abril',5=>'Maio',6=>'Junho',7=>'Julho',8=>'Agosto',9=>'Setembro',10=>'Outubro',11=>'Novembro',12=>'Dezembro'];
$shiftLabels = ['C'=>'Completo','M'=>'Manhã','T'=>'Tarde','TE'=>'Tarde extra'];
$first = new DateTimeImmutable(sprintf('%04d-%02d-01', $year, $month));
$previous = $first->modify('-1 month'); $next = $first->modify('+1 month');
$offset = (int)$first->format('N') - 1; $days = (int)$first->format('t');
$success = $_SESSION['schedule_success'] ?? null; $error = $_SESSION['schedule_error'] ?? null;
unset($_SESSION['schedule_success'], $_SESSION['schedule_error']);
?>
<!DOCTYPE html><html lang="pt"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Escala do Parque</title><link rel="stylesheet" href="/enfermaria/public/assets/css/layout.css">
<style>
body{margin:0;background:#f3f7fc;color:#16324f;font-family:'Segoe UI',sans-serif}.page{max-width:1300px;margin:auto;padding:28px 20px}.toolbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px}.toolbar h1{margin:0;color:#1f6feb}.month-nav{display:flex;align-items:center;gap:14px}.month-nav a,.btn{border:0;border-radius:8px;background:#1f6feb;color:#fff;text-decoration:none;padding:10px 14px;font-weight:600;cursor:pointer}.calendar{display:grid;grid-template-columns:repeat(7,1fr);background:#d9e4f2;gap:1px;border:1px solid #d9e4f2;border-radius:12px;overflow:hidden}.weekday{background:#eaf2fc;text-align:center;padding:10px;font-weight:700}.day,.empty{background:#fff;min-height:130px;padding:9px}.day{cursor:pointer}.day:hover{background:#f7fbff}.day-number{font-weight:800;margin-bottom:7px}.entry{font-size:12px;padding:5px 7px;margin:4px 0;border-radius:6px;background:#edf4ff;border-left:4px solid #1f6feb}.entry.extra{border-color:#e69100;background:#fff7e6}.flash{padding:12px;border-radius:8px;margin-bottom:15px;background:#e8f7ed;color:#176b36}.flash.error{background:#fdecec;color:#a12828}.modal{display:none;position:fixed;inset:0;background:#10233d99;z-index:2000;padding:24px;align-items:center;justify-content:center}.modal.open{display:flex}.dialog{background:#fff;border-radius:14px;width:min(650px,100%);max-height:90vh;overflow:auto;padding:22px}.dialog-head{display:flex;justify-content:space-between;align-items:center}.close{background:none;border:0;font-size:28px;cursor:pointer}.nurse-row{display:grid;grid-template-columns:minmax(150px,1fr) 190px;gap:12px;align-items:center;border-top:1px solid #e2e8f0;padding:10px 0}.nurse-row select{padding:8px;border:1px solid #cbd7e6;border-radius:7px}.actions{text-align:right;margin-top:16px}.hint{color:#65768c;font-size:14px}@media(max-width:800px){.calendar{grid-template-columns:1fr}.weekday,.empty{display:none}.day{min-height:80px}.toolbar{align-items:flex-start;gap:15px;flex-direction:column}.nurse-row{grid-template-columns:1fr}}
.import-card{display:flex;justify-content:space-between;align-items:center;gap:20px;background:#fff;border:1px solid #d9e4f2;border-radius:12px;padding:18px;margin-bottom:18px}.import-card h2{margin:0 0 5px}.upload-form{display:flex;align-items:center;gap:10px}.upload-form input{max-width:260px}@media(max-width:700px){.import-card,.upload-form{align-items:stretch;flex-direction:column}}
</style></head><body>
<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="page"><div class="toolbar"><div><h1>Escala do Parque</h1><div class="hint">Clique num dia para definir os enfermeiros e os turnos.</div></div><div class="month-nav"><a href="<?= $baseUrl ?>?route=park_schedule&year=<?= $previous->format('Y') ?>&month=<?= $previous->format('n') ?>">‹</a><strong><?= $monthNames[$month] ?> <?= $year ?></strong><a href="<?= $baseUrl ?>?route=park_schedule&year=<?= $next->format('Y') ?>&month=<?= $next->format('n') ?>">›</a></div></div>
<?php if ($success): ?><div class="flash"><?= htmlspecialchars($success) ?></div><?php endif; ?><?php if ($error): ?><div class="flash error"><?= htmlspecialchars($error) ?></div><?php endif; ?>
<section class="import-card"><div><h2>Importar horário em PDF</h2><div class="hint">O sistema reconhece a grelha M, T, C e TE e permite confirmar os nomes antes de substituir o mês.</div></div><form class="upload-form" method="post" enctype="multipart/form-data" action="<?= $baseUrl ?>?route=park_schedule_import"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['park_schedule_csrf']) ?>"><input type="file" name="schedule_pdf" accept="application/pdf,.pdf" required><button class="btn" type="submit">Analisar PDF</button></form></section>
<div class="calendar"><div class="weekday">Seg</div><div class="weekday">Ter</div><div class="weekday">Qua</div><div class="weekday">Qui</div><div class="weekday">Sex</div><div class="weekday">Sáb</div><div class="weekday">Dom</div>
<?php for($i=0;$i<$offset;$i++): ?><div class="empty"></div><?php endfor; ?>
<?php for($day=1;$day<=$days;$day++): $date=sprintf('%04d-%02d-%02d',$year,$month,$day); $items=$assignmentsByDay[$date]??[]; ?>
<div class="day" data-date="<?= $date ?>" data-label="<?= sprintf('%02d/%02d/%04d',$day,$month,$year) ?>"><div class="day-number"><?= $day ?></div><?php foreach($items as $item): ?><div class="entry <?= $item['shift_type']==='TE'?'extra':'' ?>" data-nurse="<?= (int)$item['nurse_user_id'] ?>" data-shift="<?= htmlspecialchars($item['shift_type']) ?>"><strong><?= htmlspecialchars($item['full_name']) ?></strong><br><?= htmlspecialchars($shiftLabels[$item['shift_type']] ?? $item['shift_type']) ?></div><?php endforeach; ?></div>
<?php endfor; ?></div></main>
<div class="modal" id="modal"><div class="dialog"><div class="dialog-head"><div><h2 id="modal-title">Editar dia</h2><div class="hint">Deixe “Sem escala” para remover o enfermeiro deste dia.</div></div><button class="close" type="button" aria-label="Fechar">×</button></div>
<form method="post" action="<?= $baseUrl ?>?route=park_schedule_save&year=<?= $year ?>&month=<?= $month ?>"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['park_schedule_csrf']) ?>"><input type="hidden" name="work_date" id="work-date">
<?php foreach($nurses as $nurse): ?><label class="nurse-row"><strong><?= htmlspecialchars($nurse['full_name']) ?></strong><select name="shifts[<?= (int)$nurse['id'] ?>]" data-nurse-select="<?= (int)$nurse['id'] ?>"><option value="">Sem escala</option><?php foreach($shiftLabels as $value=>$label): ?><option value="<?= $value ?>"><?= $label ?></option><?php endforeach; ?></select></label><?php endforeach; ?>
<?php if (!$nurses): ?><p>Não existem enfermeiros aprovados disponíveis.</p><?php endif; ?><div class="actions"><button class="btn" type="submit" <?= !$nurses?'disabled':'' ?>>Guardar dia</button></div></form></div></div>
<script>
const modal=document.getElementById('modal'),dateInput=document.getElementById('work-date'),title=document.getElementById('modal-title');
document.querySelectorAll('.day').forEach(day=>day.addEventListener('click',()=>{document.querySelectorAll('[data-nurse-select]').forEach(s=>s.value='');day.querySelectorAll('.entry').forEach(e=>{const s=document.querySelector('[data-nurse-select="'+e.dataset.nurse+'"]');if(s)s.value=e.dataset.shift});dateInput.value=day.dataset.date;title.textContent='Escala de '+day.dataset.label;modal.classList.add('open')}));
function closeModal(){modal.classList.remove('open')} document.querySelector('.close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
</script></body></html>
