<?php
$monthNames = [1=>'Janeiro',2=>'Fevereiro',3=>'Março',4=>'Abril',5=>'Maio',6=>'Junho',7=>'Julho',8=>'Agosto',9=>'Setembro',10=>'Outubro',11=>'Novembro',12=>'Dezembro'];
$shiftLabels = ['M'=>'Manhã (10:00–13:45)','T'=>'Tarde (14:00–18:00)','C'=>'Completo (10:00–18:00)','TE'=>'Tempo extra (13:00–encerramento)'];
?>
<!DOCTYPE html><html lang="pt"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Confirmar importação</title><link rel="stylesheet" href="/enfermaria/public/assets/css/layout.css"><style>
body{margin:0;background:#f3f7fc;color:#16324f;font-family:'Segoe UI',sans-serif}.page{max-width:1100px;margin:auto;padding:28px 20px}.card{background:#fff;border:1px solid #d9e4f2;border-radius:14px;padding:22px;margin-bottom:18px}.mapping{display:grid;grid-template-columns:1fr 1.5fr;gap:12px;align-items:center;border-top:1px solid #e3ebf5;padding:10px 0}.mapping select{padding:9px;border:1px solid #bdcadb;border-radius:7px}.btn{display:inline-block;border:0;border-radius:8px;background:#1f6feb;color:#fff;text-decoration:none;padding:11px 16px;font-weight:700;cursor:pointer}.btn.secondary{background:#64748b}.actions{display:flex;justify-content:flex-end;gap:10px}.summary{display:flex;gap:30px;flex-wrap:wrap}.warning{padding:12px;background:#fff7e6;color:#854d0e;border-radius:8px;margin-bottom:16px}@media(max-width:650px){.mapping{grid-template-columns:1fr}.actions{justify-content:stretch}.btn{flex:1;text-align:center}}
</style></head><body><?php require __DIR__ . '/../layouts/header.php'; ?><main class="page"><h1>Confirmar importação</h1><div class="card"><div class="summary"><div><strong>Mês</strong><br><?= $monthNames[$import['month']] ?> <?= (int)$import['year'] ?></div><div><strong>Turnos encontrados</strong><br><?= count($import['entries']) ?></div><div><strong>Enfermeiros no PDF</strong><br><?= count($activePdfNames) ?></div></div></div>
<form method="post" action="<?= $baseUrl ?>?route=park_schedule_import_confirm"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['park_schedule_csrf']) ?>"><div class="card"><h2>Associar enfermeiros</h2><p>Confirme a pessoa correspondente a cada nome do PDF.</p><?php if ($unmatchedCount): ?><div class="warning"><?= $unmatchedCount ?> pessoa(s) serão criadas a partir do PDF se não escolher uma associação existente.</div><?php endif; ?>
<?php foreach($activePdfNames as $pdfName): $suggested=$suggestions[$pdfName]??0; ?><label class="mapping"><span><strong><?= htmlspecialchars($pdfName) ?></strong><?php if (!empty($import['contacts'][$pdfName])): ?><br><small><?= htmlspecialchars($import['contacts'][$pdfName]) ?></small><?php endif; ?></span><select name="mapping[<?= htmlspecialchars(base64_encode($pdfName)) ?>]" required><option value="">Escolher pessoa…</option><option value="new" <?= !$suggested?'selected':'' ?>>Criar “<?= htmlspecialchars($pdfName) ?>” a partir do PDF</option><?php foreach($nurses as $nurse): ?><option value="<?= (int)$nurse['id'] ?>" <?= $suggested===(int)$nurse['id']?'selected':'' ?>>Associar a <?= htmlspecialchars($nurse['full_name']) ?></option><?php endforeach; ?></select></label><?php endforeach; ?></div><div class="card"><h2>Resumo por turno</h2><?php $counts=array_count_values(array_column($import['entries'],'shift')); foreach($shiftLabels as $code=>$label): ?><p><strong><?= $code ?></strong> — <?= $label ?>: <?= (int)($counts[$code]??0) ?></p><?php endforeach; ?></div><div class="actions"><a class="btn secondary" href="<?= $baseUrl ?>?route=park_schedule&year=<?= (int)$import['year'] ?>&month=<?= (int)$import['month'] ?>">Cancelar</a><button class="btn" type="submit">Confirmar e importar</button></div></form></main></body></html>
