name: SAE CI

on:
  push:
  pull_request:

jobs:
  php-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, gd

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist

      - name: PHP syntax check
        run: find src -name "*.php" -exec php -l {} \;

      - name: Run PHPStan
        run: php vendor/phpstan/phpstan/phpstan analyse

      - name: Basic sanity
        run: php -r "echo 'OK';"
